### ISSUE TITLE
Improper conflations between "platform" and "host"

### ISSUE THREAD

**Issue by theDanielJLewis** [Podcastindex-org/podcast-namespace#1]
I see some potential misuses of the term "platform." For example, Apple Podcasts, Google Podcasts, Spotify, and such _are_ platforms. But Captivate, Fireside, and such are hosting-providers.

Also, there can be easy confusion with the word "host." For example, is "podcast host" the person hosting the podcast, or the company hosting the media files? The way I distinguish these two things is using "podcast host" to refer to the person and "podcast-hosting provider" to refer to the company.

**Comment by daveajones** [comment]
Would changing:

<podcast:id platform="[host slug]">

to:

<podcast:id service="[service slug]">

...clear up the confusion?

**Comment by theDanielJLewis** [comment]
What do you _actually_ want the data to contain? If you want the ID for that podcast on each app/platform, then I think sticking with `platform` would be best.

**Comment by daveajones** [comment]
What I want is a list of the identifiers on each platform to be listable in the feed.  I want to be able to read the feed and extract the itunes id, the blubrry id, the google id, the captivate id, etc.  Basically any service, host or directory that feed is listed in should be able to be shown with this tag so that the whole world can stop scraping iTunes and the other directories to get this info that the feed owner/host already knows.

**Comment by theDanielJLewis** [comment]
Yes, I think that should then be `platform` or `catalog`.

**Comment by daveajones** [comment]
I went with “service”. I know it’s not the most accurate in all cases. But it seems the most flexible.
