### ISSUE TITLE
ChapterJson: Find better name for 'chapters'

### ISSUE THREAD

**Issue by saerdnaer** [Podcastindex-org/podcast-namespace#103]
In books chapters are used to structure the content, now with https://github.com/Podcastindex-org/podcast-namespace/blob/main/chapters/jsonChapters.md and the `toc: false` we also are able to use them to display an image or link inside of an chapter. Thereby not all entries in the list are chapters, so we should find a better name e.g. 'marks', 'entries', or what ever. Compare also https://twitter.com/PodcastindexOrg/status/1324557245271756802 

Before:
```
{
    "version": "1.1.0",
    "chapters": []
}
```

After:
```
{
    "version": "1.1.0",
    "entries": []
}
```

Relates to: #47

**Comment by daveajones** [comment]
Your reasoning makes sense. But the industry has accepted that this type of behavior is a “chapter”.  I don’t think we can change it without causing confusion.  It follows the spirit of the MP3 chapters spec, so I think we’re stuck with the name as it is.

**Comment by yradunchev** [comment]
Agree about MP3 spirit. It also creates an association between podcasts and audio-books. In my opinion both not exactly bad but not exactly good also. Since podcasting is also closer to broadcasting (...distribution of audio or video content to a dispersed audience via any electronic mass communications medium,... in a one-to-many model.) probably we can 'borrow' from radio program terms and instead of 'chapter' we can use 'block' as in 'unit/section of content' and as in [Merriam-Webster(8:a)](https://www.merriam-webster.com/dictionary/block) definition of the term:

_A quantity, number, or section of things dealt with as a unit_
- bought a large block of shares
- a half-hour block of music a half-hour block of music 
- a block of text

**Comment by Majester** [comment]
Radio and theatre also use _Act_ or _Part_ for a segment or section of a performance.
