### ISSUE TITLE
Proposal: Language Tag or extend Location (Tag)

### ISSUE THREAD

**Issue by swschilke** [Podcastindex-org/podcast-namespace#107]
It would be beneficial to have one or more Language tags in the podcast RSS (general, for the Podcast the main language) and item / episode level (like language for this episode). Refering to rfc4646 / rfc4647 or  ISO_639-2

If the Location tag get's extended it should be a subtag there.

Sorry if I overlooked something and this tag is already available.

**Comment by douglaskastle** [comment]
I don't think this should be in the location tag.  The language the people are using and the location that they are covering could be different, and that is a good thing.  

I think this should either get it's own tag, or maybe it could be folded into the person tag.  Most people only speak one language, but especially when they podcast if they are multilingual they will still speak one one per podcast (there are I am sure many exceptions to that, but I am speaking to the general case.)

Language, if you don't use the default of US English on YouTube, has a major break out option when uploading a video.

**Comment by jamescridland** [comment]
There is a `<language>` tag already set in RSS at the channel level. It's already widely supported.

While individual episodes *can* be in different languages in the same feed, it is quite unusual. That's unsupported, and I'm not sure I see a compelling reason to enable or encourage that.

**Comment by jamescridland** [comment]
If it's OK, @swschilke , I'm going to close this discussion, since I'm trying to encourage the disparate discussions around `location` to coalesce in https://github.com/Podcastindex-org/podcast-namespace/issues/138

**Comment by swschilke** [comment]
It's not okay, as long as language is not covered in #138 - language is something different than location. I can be from DE but the podcast is in EN ! Reflect the demand for a language field in #138 then you can close this.

Kind regards

.

**Comment by jamescridland** [comment]
"I can be from Germany but the podcast is in English"

Indeed. The '<language>' tag [already exists in the base RSS specification](https://validator.w3.org/feed/docs/rss2.html#requiredChannelElements). So, your podcast's feed would read, in part:

```xml
<channel>
 <title>swschilke's podcast</title>
 <description>My podcast</description>
 <language>en</language>
 <podcast:location>
   rel="from"
   description="Frankfurt, Germany"
   geo="geo:50.1106444,8.6820917"
   osmid="R62400"
 >
</channel>
```

Currently the RSS specification does not allow the "language" in an individual 'item'. Most multilingual podcasts out there appear to have separate feeds per language, since the amount of someone who speaks both English *and* German will be significantly lower than the amount of people who speak just one of those languages.

As you say, language is different from location, and I don't quite understand the benefit of the language being in a tag that is meant to discuss a location. Could you help me understand?

Alternatively, would you be happy to suggest an extended language tag to go into an 'item', if that's your intention?
