### ISSUE TITLE
<podcast:funding>

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/podcast-namespace#12]
I would like to suggest the inclusion of a funding tag, that could be added multiple times.
it should be added under `channel`.

I suggest the following format:

`<podcast:funding platform="[platform slug]" url="[url for the show at the platform]" name="[platfrom name]">[podcast handle at the platform]</podcast:funding>`

example: `<podcast:funding platform="patreon" url="https://patreon.com/somecast" name=Patreon>somecast</podcast:funding>`

There is some redundancy, but it is intentional, the platform name and url are present so that clients can show information and navigate to it without knowing anything about the platform. The platform slug and podcast handle at the platform would allow for a better integration in case of existing APIs.

Additionally, this tag could support funding with cryto currencies with the same format, example: `<podcast:funding "wallet.XBT" text="Bitcoin">1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2`</podcast:funding>

Reference: https://github.com/socialrss/socialrss/blob/master/DOCUMENTATION.md

**Comment by daveajones** [comment]
Good.  I'm going to put this in the phase 2 area since it needs to be open for comments for a bit.  I'm sure people will have comments, but this seems quite succinct to me as a starting point.

**Comment by jamescridland** [comment]
This is nice.

I wonder whether I might suggest "title" for a short explanation of funding elements?

Example:
```
<podcast:funding platform="patreon" title="Support us on Patreon" url="https://patreon.com/somecast" name=Patreon>somecast</podcast:funding>
<podcast:funding platform="teespring" title="Buy our merch" url="https://teespring.com/somecast" name=Patreon>somecast</podcast:funding>
```

**Comment by daveajones** [comment]
I can see that @jamescridland . Will do.

**Comment by theDanielJLewis** [comment]
I would favor `label` over `title`.

**Comment by tomrossi7** [comment]
I love this feature! Do we need to include the `platform` since it is just a function of the URL?

It would cut back on code and leave the standard open to whatever URL people want to provide. For example, we have podcasters that have their own payment system set up on their website and link to it (e.g. https:://mydomain.com/give).

**Comment by daveajones** [comment]
Seems like a trade off to me.  The idea of the platform="" was to use pre-defined slugs to keep from having to dig out the name from the url.  The title was so the podcast owner could make something displayable.  Like title="Buy our Merch!"  Also, since it's both a channel level and item level element, the title could differentiate that this is the donation link for a guest on the show and not the podcaster.  Otherwise you wouldn't know.

We could make all attributes here optional and put the url as the value.  Might be a good middle-ground.  Like so:

`<podcast:funding platform="[service slug]" title="[user provided note]">[url for the show at the platform]</podcast:funding>`

**Comment by theDanielJLewis** [comment]
I wonder if this kind of tag might need a slight rename so that it could be used at the `<item>` level to link to episode-level sponsors or products.

`<podcast:moneybags>`? 🤑

**Comment by dellagustin** [comment]
> I wonder if this kind of tag might need a slight rename so that it could be used at the `<item>` level to link to episode-level sponsors or products.
> 
> `<podcast:moneybags>`? 🤑

I would use separate tags for direct funding and sponsored links.

**Comment by dellagustin** [comment]
> Seems like a trade off to me. The idea of the platform="" was to use pre-defined slugs to keep from having to dig out the name from the url. The title was so the podcast owner could make something displayable. Like title="Buy our Merch!" Also, since it's both a channel level and item level element, the title could differentiate that this is the donation link for a guest on the show and not the podcaster. Otherwise you wouldn't know.
> 
> We could make all attributes here optional and put the url as the value. Might be a good middle-ground. Like so:
> 
> `<podcast:funding platform="[service slug]" title="[user provided note]">[url for the show at the platform]</podcast:funding>`

In my original suggestion the purpose of having "[podcast handle at the platform]" was to facilitate the integration with platform specific APIs, under the assumption that such handle would be commonly used by the APIs, but I did not look for references of such usages.

Anyway, if we find usage for it, it could be added as a parameter later in a backwards compatible way.

The current format would also work for funding with crypto currencies, the tag value could be the wallet address.

**Comment by daveajones** [comment]
Sounds good.  Let's move forward with it then.  And, we can adjust in a future phase if needed.
