### ISSUE TITLE
Focus for Phase 2

### ISSUE THREAD

**Issue by daveajones** [Podcastindex-org/podcast-namespace#120]
I propose that the main focus for Phase 2 tags should be:

`<podcast:person>`
`<podcast:location>`
`<podcast:season>`

Those seem to be the ones with the most push right now.  

I also see a big benefit with `<podcast:archive>`.  Seems like low-hanging fruit.

**Comment by npruzaniec** [comment]
Agreed on solving `<podcast:archive>` but still feel this is better solved with a standard for URL query strings using paging values or episode offsets.

The other three seem doable as well. I think the discussion around `<podcast:location>` has been pretty fuzzy. Can we define what that would be? LatLong, Country/Region/City, just a country code? Can this/should this include `<language>` somehow as many languages are regional dialect specific?

**Comment by jamescridland** [comment]
For `<podcast:location>` I'd be keen to move this forward. https://github.com/Podcastindex-org/podcast-namespace/issues/138 has a new proposal which includes many of the discussions here, and a few clear use-cases.

I'd also like to suggest `<podcast:id>` as a simple one that we can push forward. The reason I'm keen to see this be used is partly selfish - it would sure make my life easier! - but also because it is easy for every podcast host to achieve with no change of user-facing UX. It's super-easy to implement, and would be a good, quick, way to achieve significant takeup of this namespace.

**Comment by daveajones** [comment]
I adjusted the main README to show that we're focusing phase 2 on `location`,`person`,`id`,`season` and `social`.  Social might be a little ambitious and we can boot it if that seems prudent.  Just throwing it in there for now.  Season is low hanging fruit, but I think it needs a `podcast:episode` tag to match it.
