### ISSUE TITLE
Proposal <podcast:version> -tag

### ISSUE THREAD

**Issue by 419monk** [Podcastindex-org/podcast-namespace#122]
**Summary**
I propose a new tag: `<podcast:version>3</podcast:version>`.
It would live under `item`-tags. Changing the content of the `version`-tag would indicate that some content in the episode has changed and the item should be reprocessed by the app.

**Motivation**
It seems pretty common that after publishing an episode something needs to be changed. For example: Audio is somehow messed up -> you need to reupload the audio file. Seems that many of the players then fail to redownload the enclosure. Or at least the url needs to be changed. Other common way to make apps reprocess the item is to change it's `guid`, but that leads to duplicate download of the episode since `guid` is pretty much the only way to uniquely identify an episode.

So `<podcast:version>`-tag would be a way to communicate that this episode is the same episode that you have possibly already downloaded, but there is something new or changed and it needs to be downloaded and processed again.

**Simple version**
The most simple version would be to have only one `<podcast:version>`-tag per episode that would tell that something has changed and everything needs to be reprocessed and redownloaded.

**More complex alternatives**
We could also have version-tags or attributes for individual child tags of `item`. For example if transcripts or captions have changed, it would not be necessary to download the enclosure again. 

**Alternate possible names for the tag**
- `<podcast:revision>`

**Tag content**
The tag content could be for example a number, but maybe it does not matter what the content is. A timestamp of the change could be used. I guess it would work so that the app would store the version with cached audio-file and other resources and if the stored version is different than one found in the feed, the app would refresh everything (or part of) stored things related to the item.

**Examples of the content that would need to be refreshed when version changes**
- Audio file / enclosure
- Transcriptions / captions
- Album art
- Soundbites
- Possible cached show note / description images
- Chapters

**Comment by theDanielJLewis** [comment]
I disagree on the need for this because there's already a way to do this within the standard RSS spec: the GUID tag.

Yes, if you replace the audio file, usually even changing the file name, only _new_ downloaders will get the replacement file. That's fine when it's a minor fix, like maybe you left in a minute of silence at the end.

But for more serious problems, you would replace the audio _and_ change the GUID tag.

A different GUID is what triggers nearly all podcast apps to recognize the episode as new (even if it's the same title and enclosure URL) and force a redownload. This is often necessary when the previous version was catastrophically bad that you want to inconvenience everyone who already downloaded it because they _absolutely need_ the fixed version.

**Comment by daveajones** [comment]
Changing the GUID often creates duplicate episodes on many aggregators, even if you delete the old episode.  Because, for high volume aggregation, deleting is expensive.

**Comment by johnspurlock** [comment]
In cases of inline description, enclosure url, or any other item-level tag changing, that info is already available inside the feed, right?  I'm not sure what another tag would accomplish.  Parsing <version> vs parsing <enclosure> is the same cost, both can be done while parsing the feed.

Good feed aggregators can pick up updates by noticing these changes, the GUID should remain constant to make it clear that the intent is an update, not a new episode.

The fact that lazy feed aggregators sometimes skip processing updates when they encounter a GUID they've already seen should not be a rationale for breaking the notion of stable item identity (GUID) for well-behaved clients.  The latter is far more important, since every other client will recognize this as a conceptually new item, and every use of these clients will have what looks like a duplicate episode to deal with.

**Comment by theDanielJLewis** [comment]
"Duplicates" are dependent on context. If someone has already downloaded the "bad" media and you change the GUID for the "good" replacement, the podcast app will, rightly, download the new version. But if the app has not downloaded anything yet, it will see only the new version in the RSS feed (whether you make it "new" by changing the GUID or simply replacing the enclosure URL, or replace the file with the same name).

Yes, a small number of aggregators cache the feed information and will thus not update to reflect the contents of the feed when anything is removed. That's the fault of the app, not the feed (or the RSS spec). I think it would be better to encourage these apps to support the decades-old RSS spec and standard support than to get them to support a new tag.

… and I ruined my cooking egg nog in order to share my thoughts on this. That's how much I care about getting this right. 😃

**Comment by johnspurlock** [comment]
Something else to consider: a tag called `<podcast:updated>` (or `<podcast:updateTime>` etc) would be a good way to both serve the conceptual idea of versioning an existing item in a naturally comparable way, while also carrying a useful human-readable payload.

Basically atom's `<updated>` vs `<published>` (which is equiv to rss `<pubDate>`).  The [description for `<updated>`](https://tools.ietf.org/html/rfc4287#section-4.2.15) in that spec seems very similar to what seems to be desired here.

Still would want to clarify the semantics of updating this value.  Would it be changed after a tweak to the item's `<title>`, for example?  It would appear to be most useful for identifying changes to external resources, i.e. pointers to chapter json urls, or enclosure urls that do not change in the feed, but whose contents have changed.

**Comment by 419monk** [comment]
@theDanielJLewis Sorry about your eggs man.

Good points here. I agree with most of them.
- No great benefit of a field telling that information already in the item-tag like title has changed
- Although personally I don't really like the guid being changed to force reprocessing, it's just a fact that podcasters will need to support non podcast 2.0 clients far in the future and if that is the only mechanism for forcing redownload then podcasters will need to do that to serve the non podcast 2.0 clients. So it does not do much good to have an extra tag to facilitate the same thing, even if it would be smarter way overall (of course it's debatable if it would be smarter, but even if it was)

But as @johnspurlock mentioned there are the mostly new external things. Chapters, transcripts and so on. Do they have any planned mechanisms to force or suggest reprocessing? As those are mostly part of podcasting 2.0 it would possibly make more sense to have podcasting 2.0 features to enable force reload. Or are they supposed to be downloaded every time feed is parsed again? Of course they payload for chapters or even transcripts are small compared to the actual enclosure-file, but if there are lots of episodes like there most likely are, it might make sense to only redownload them when they have been changed.
Or is the idea to change the url every time content changes? Or is there anything in the spec about updating things? I need to take a look and maybe it would be better to open new issues regarding each feature.

**Comment by 419monk** [comment]
I opened a new issue to open discussion about refreshing external resources here: #126 

Will close this now.
