### ISSUE TITLE
The numerical split in the <podcast:value> tag

### ISSUE THREAD

**Issue by brianoflondon** [Podcastindex-org/podcast-namespace#128]
At the moment the spec says that the split should be a percentage. I think it should be just a numerical value and split is determined in use.

If an app developer or host wants to transparently give the option to contribute or perhaps (in return for a free or subsidised hosting account) force a split, perhaps we should just say that the split number represents the share at that level.

If someone's tags don't add up to 100, that is of no significance as long. If I had ```split = 33``` for me and ```split = 1``` for podcastindex, assuming no other entires, that would be 97% to 3% without needing to make sure everything added up to 100.

```
 <podcast:value type="lightning" method="keysend" suggested="0.00000005000">
  <podcast:valueRecipient name="podcaster" type="node" address="036d33fbd386acc37577a6d72fea0e893e94a915139508d52a0395a930e1a6b613" split="99" />
  <podcast:valueRecipient name="podcastindex" type="node" address="036557ea56b3b86f08be31bcd2557cae8021b0e3a9413f0c0e52625c6696972e57" split="1" />
</podcast:value>
```

**Comment by daveajones** [comment]
I’ve thought along these lines as well. Mostly considering when someone down the chain adds a split (like 1%) and then the original feed has its value block messed up so that the original doesn’t come through. When it’s an interdependent percentage mix it ends up throwing the math off. It can be fragile.

**Comment by brianoflondon** [comment]
I don't think it's fragile, I just think we might need to be explicit at the base layer which will be the ```<podcast:value>``` tag.

Everything down up the line should be percentages that are calculated and peeled off before whatever ends up back at the base layer which gets divided up as calculated in whichever app is receiving value for it.

**Comment by douglaskastle** [comment]
Yes I was thinking about this with regard to lets say podcast related value recipients versus episode related ones.  You may have different recipients per episode, with different splits.  That would make trying to get the whole total to add up to 100 impossible via explicit values.

I suppose what ever is constructing the RSS feed could calculate the total and then divide the splits so that what is in the feed always adds up to 100 , you may want to at least, in this case make the split a float instead of an int. So you may add a guest, and assign them a value, the ratio of what goes into the other respective fields would then get reduced accordingly

When it comes to any thing crypto, or maybe just money, it does put a target on your back for hacking.  This might move the goal posts if some one could insert a fake guest, with a huge number for a split/ratio.  Your other address values look the same, but everything gets drained into the "guest" address.  Not too sure what the protection is though.

**Comment by brianoflondon** [comment]
I probably should open another Issue related to the security implications of the ```<podcast:value>``` tag. I'm thinking that some sort of 2nd factor authentication and confirmation of the main value recipient at least might be necessary perhaps with a DNS entry.

The problem of a hijacked feed with an altered value tag becomes a big problem.

**Comment by daveajones** [comment]
We are looking at key signing the block. Just haven’t gotten there yet. It’s next in the discussion.

I also like the DNS approach of having perhaps a TXT entry that holds a hash of the block as a verification step. That gets messy with episode level value blocks though.

At the index level, we ignore any value block in a non-https feed. So the block could also be signed with the TLS certificate.

**Comment by douglaskastle** [comment]
This feels like to me it is the node processors job.  The node is what receives and sends the sats to the correct destinations, not the RSS feed which is just similar to a public key library. So the podcaster would have to approve every address with them before it can be used.  If the address isn't approved, it isn't used.  This would also leave it fall to the node processor to resolve all the various ratios.  Only the approved addresses are used.

This obviously can't go in the spec, because it is not the fault of the spec if the website is hacked, but real world implementation of this one can be so badly done and bring a lot of bad press.

**Comment by npruzaniec** [comment]
> At the index level, we ignore any value block in a non-https feed. So the block could also be signed with the TLS certificate.
Glad to hear this, was just thinking about issues with non-https feeds today.

> I also like the DNS approach of having perhaps a TXT entry that holds a hash of the block as a verification step. That gets messy with episode level value blocks though.
Also, don't forget, DNS is generally not secure either. I know something doesn't have to be perfect for it to be good, but generally not good practice to rely on DNS values for cryptographic verification at this point.

**Comment by dergigi** [comment]
Considering that the [value spec](https://github.com/Podcastindex-org/podcast-namespace/blob/main/value/value.md#payment-calculation) now reads as follows:

> If, instead of a 50/40/10 (total of 100) split, the splits were given as 190/152/38 (total of 380), the respective payment amounts each minute would still be 50 satoshis, 40 satoshis and 10 satoshis because the listener chose to pay 100 satoshis per minute, and the respective shares (as a percentage of the total) would remain the same.

...I believe this issue can be closed?

**Comment by daveajones** [comment]
10-4
