### ISSUE TITLE
Shared and subscribe-able block lists.  

### ISSUE THREAD

**Issue by brianoflondon** [Podcastindex-org/podcast-namespace#148]
This is a somewhat defensive idea and far out but one I want to raise for discussion. [I've given more background and used more emotive language in a blog post over on Hive](https://peakd.com/hive-136933/@brianoflondon/how-to-allow-censorship-of-podcasting-2-0).

# The Subscrib-able or Shared Block List for Podcasts

I propose to produce a standard which allows any organisation so desirous of it to create and maintain a list of banned podcasts. This could be a JSON or OPML/XML list. We don't need to build the software to create and maintain these lists, let the censorious ones hire some devs to do that for them.

On the Podcast app and Podcast Index side, as a purely defensive measure, if someone voluntarily OPTS to "follow" a shared block list, search results from content that appears on the blocked list are never shown and subscriptions to blocked content are prohibited or deleted.

But the important point is the OPTION to safely filter is there, without it being turned on by default.

Just to lay out how this would work: the ADL or SPLC don't want me to listen to something because of harms, I can subscribe to their block lists and be saved from whatever might harm me.

For all normal people and, what I believe to be the VAST majority, nobody will use this feature.

The point is, however, when Google and Apple are being asked to ban apps from the app stores because Woke, or China doesn't like Winnie the Po memes, app devs have a defence: people are free to subscribe to the ADL/SPLC or even Google or Apple list and they won't see anything YOU don't want them to see. Shift the onus onto the censorious to get people to subscribe to their censorship list!

We also know the job of maintaining such a block list would be like pushing shit uphill in the rain with ones nose. And I wish them every success in their task of regulating the Internet.

**Comment by jamescridland** [comment]
It's clear you're not serious with this proposal with your derogatory choice of words. However, there's something to be discussed here, perhaps.

It's certainly the case that the index could have legal proceedings taken against it, if it links to illegal content. "Illegal content" in some territories is content that is rude about the King (if you're in Thailand), content against the German Strafgesetzbuch (like symbols of specific banned groups), or content that puts people in danger, like those breaking the Official Secrets Act of the UK (which could put either the country or those working for it into threatening situations).

This makes use of Podcast Index by app developers problematic, since an innocent browse or search could come up with content which may get the app developers into significant trouble. It's one of the reasons why many podcast apps use Apple's lists.

The way I've seen some indexes deal with this is to mark these in such a way that they don't come up in search unless you deliberately type the exact name. So a show can be 'shadow-banned', if you like: the "I Love Killing Kittens" podcast only appears in a search result if you search for the exact name, and by searching for "killing kittens" it won't appear. 

As one example - here's [Marco from Overcast](https://overcast.fm/podcasterinfo):

> Since Overcast is a one-person company that can’t possibly review and monitor all known podcasts for spam, adult content, hate speech, and other problematic, controversial, or illegal material, Overcast uses the human-reviewed Apple Podcasts directory as its filter for what should be included in search results and recommendations.
> 
> In rare cases, a show may be included in Apple Podcasts that does not comply with its content requirements. If I’m notified that Apple’s guidelines are being significantly violated by a show that is (but should not be) in their Podcasts directory, I may manually remove it from Overcast’s search results and recommendations.

It would be disappointing if Podcast Index LLC gets sued out of existence just because it linked to an illegal podcast. (Which is not beyond the realms of possibility).

This is something for Dave/Adam to consider (and whoever else are directors of Podcast Index LLC). I'm sure that they have done; as they're both US citizens, they do have laws to follow, after all.

**Comment by brianoflondon** [comment]
>It's clear you're not serious with this proposal with your derogatory choice of words. However, there's something to be discussed here, perhaps.

I am being serious but I try to maintain a readable style beyond the dry technicalities of code and law, perhaps too much in this case <sup>1</sup>.

Indexes and search index's (like Google) have long since managed to dodge liability for content they link to and Section 230 is also in play for the US. If presented with a legally obtained warrant from any jurisdiction, however, I can see that Podcast Index would have to take down links or raise funds to fight.

My raising this was more to do with the sub-legal but heavily oppressive censorship demands we're seeing all the time though I agree a system like this would help with the more serious State level demands for censorship at least in an overt and transparent way to people outside of the censoring jurisdictions. The censor lists would need to be public by their nature for them to be shared across the entire Podcast ecosystem.

-----



<sup>1</sup>I wrote this while multitasking the fixing of a legal transcript from a somewhat excruciating 1hr40mins of explaining the mechanics of blockchain mining and influences on blockchain price movements to a high court judge in Australia.

**Comment by jamescridland** [comment]
> Indexes and search index's (like Google) have long since managed to dodge liability for content they link to and Section 230 is also in play for the US.

Not true. Google has a myriad of laws compelling it to remove illegal material.

* [Google received requests to remove 3.8m URLs as a result of EU privacy law](https://transparencyreport.google.com/eu-privacy/overview?hl=en). It removed 53% of them.

* [Government removals including illegal content](https://transparencyreport.google.com/government-removals/overview?hl=en) are rather less visible, but still there.

The US's section 230 requires removal of copyright violations, as well as illegal material under federal law. The "good" thing about section 230 is that it doesn't require that illegal content is not published (aka pre-moderation) - but it does require that if informed about illegal content, it should be removed (aka post-moderation). That applies to Podcast Index LLC just as much as it does to someone else.

Anticipating "but it's a link to the material, not the material", I'd also remind you that many countries go so far as to compel DNS operators to remove or tamper with DNS entries to some websites, most notably The Pirate Bay.

> My raising this was more to do with the sub-legal but heavily oppressive censorship demands we're seeing all the time

The use of 'censorship' here is pejorative. I wonder whether you're merely here to argue.

> The censor lists would need to be public

To publish a list of illegal podcasts is, um, publishing a list of illegal podcasts. If the idea is to not publish links to illegal podcasts by publishing links to illegal podcasts, then that's not an idea I'd take very seriously.
