### ISSUE TITLE
general inquiry: payment

### ISSUE THREAD

**Issue by t-900-a** [Podcastindex-org/podcast-namespace#246]
Wondering why you guys chose to use <podcast:funding> instead of rel="payment"

http://microformats.org/wiki/rel-payment

**Comment by daveajones** [comment]
For clarity of purpose. This is ultimately meant to be an all inclusive namespace for all podcast specific functionality. We discussed redundancy with other tags and determined it was good to have a namespace that included all within itself so that at some point in the future apps and publishers could have confidence and simplicity.
