### ISSUE TITLE
Podcast Contact/Owner

### ISSUE THREAD

**Issue by tomrossi7** [Podcastindex-org/podcast-namespace#27]
Could the `<podcast:contact>` be used for the owner verification?

`<podcast:contact type="owner" method="email">owner@podcastindex.org</podcast:contact>`

**Comment by MartinMouritzen** [comment]
@daveajones To me, my first instinct is that this is a bit redundant to the "managingEditor" element.
I do see the difference, but I am wondering if there will realistically ever be a need to have them be separate? Personally I am leaning towards simplicity here.

**Comment by tomrossi7** [comment]
I think we should treat adding a tag like adding an amendment to the constitution -- we should do it only when necessary and after a good debate. The `<podcast:contact>`, `<managingEditor>`, and `<podcast:ownerVerification>` are close enough that they may cause confusion.

@daveajones if this email is strictly to be used with the `<podcast:locked>`, maybe we should replace the locked tag with one called `<podcast:lockedBy>[email to direct lock inquiries]</lockedBy>`? The presence of the tag tells you its locked and provides you some additional information about resolving the lock. Maybe even provide a type so that it could be an email or a link?

`<podcast:lockedBy type="email">registrar@domain.com</lockedBy>`
`<podcast:lockedBy type="link">https://podcasthost.com/locked/12345</lockedBy>`

**Comment by daveajones** [comment]
Fair warning.  The `<podcast:locked>` and `<podcast:ownerVerification>` tags are the only ones in the whole spec that I have strong feelings about. :-)

`<podcast:locked>` - We're trying to send a message with this tag.  The message is "stop pirating podcasts".  The message has to have zero ambiguity.  When podcast hosts implement the new namespace, my vision is that all of their current podcast feeds will get the `<podcast:locked>yes</podcast:locked>` inserted by default.  And, then when a customer wants to leave the platform they can unlock it.  Having it be always present with a yes or no value allows the industry to publicly shame those who choose to ignore the will of other host's user base.  There is financial harm going on, and this sends that message loud and clear.

`<podcast:ownerVerification>` - This functions along-side `<podcast:locked>`.  But, it can also be used for other types of verification.  For instance, if Patreon or some other payment platform wants to get in contact with the owner they can know for certain that this is going to land in the owner's in-box.  Because the other tag names are very old and the meaning could be ambiguous, this again is a chance to plant a flag and give everyone certainty about a truly functional verification email address.  I've heard Todd at Blubrry say they have to resort to asking the user to create an episode with a certain string in the title to verify it's them sometimes.  This is a chance to solve all of that mess.

As an example, I just pulled up a [feed](http://feeds.soundcloud.com/users/soundcloud:users:458387301/sounds.rss) at random from the index and there is no managingEditor tag at all. And, the itunes:owner-itunes:email address is "feeds@soundcloud.com".  Who knows where that goes.  If we set the spec to say managingEditor, and there isn't one listed.  Or, if the one listed is ambigous (like this example), that might leave the door open for shady hosting companies to claim that the spec is unreliable, or that the email address provided wasn't trustworthy.

I don't like making any of these tags "required".  But, these tags are as much a political statement as a technical one.

All that being said.  I'm ok with reducing it down to just:

`<podcast:locked owner="email@domain.com">yes</locked>`

or:

`<podcast:locked owner="email@domain.com">no</locked>`

But, it really has to be an email address.  Links are too fragile.  And, it has to be always present.

That way there is only one required tag and not two.  And, the intent is still very clear.

How does this sound?

**Comment by tomrossi7** [comment]
Ah! I really like that! Explicit and self-contained! You want me to write it up?

**Comment by daveajones** [comment]
> 
> 
> Ah! I really like that! Explicit and self-contained! You want me to write it up?

Absolutely.  Go for it.

**Comment by daveajones** [comment]
We're good here.
