### ISSUE TITLE
Canonical home and other links

### ISSUE THREAD

**Issue by andybeard** [Podcastindex-org/podcast-namespace#35]
I am currently an outsider to Podcasting looking in.
I have done a fair bit with video SEO, enclosures, oEmbed etc.

Historically there is the concept "All roads lead to Rome"
In SEO we think of "All roads lead to Home"

1. Home

I know you have links for the author home, and the transcript, but that isn't the home page of the actual Podcast.
i.e. the super optimized page just about the Podcast with the perfect layout, subscribe links in the order of your preference, email capture etc.
You need to have something for this.

2. Subscribe links

You should be able to specify where your Podcast resides on various services and your preferred order.
There are key issues here
1. Platforms die... you might want to prioritise services that will still be around in 5 years e.g. Apple and Spotify
2. Different services pay more per stream. Hinting for them to use 1 service over another can affect your income. e.g. Spotify then Apple

Service migration

If you are doing this namespace, you might also want at the same time as a parallel initiative ensure a standard for export and import of subscriptions between platforms

**Comment by tomrossi7** [comment]
I'm not sure this is as relevant for the RSS feed as it is for the podcast webpage -- which would be outside the scope of this standard. Sorry if I'm missing something!

**Comment by andybeard** [comment]
Imagine a time when a podcast is listed on 1000 different sites all pulling their information from the RSS feed
Many won't even have a way to create an account for the podcast owner
Even if there was a way to create an account and edit something, it isn't efficient to log into 1000 sites and make manual changes, I have had to do that with syndicated articles in the past... I stopped after about 50 and just disavowed links.

The most important link arguably is the one for Home because being able to change that if you decide to restructure a website or change hosting is imperative.

Just imagine being able to modify a tracking parameter across 1000 sites on your links in seconds, or switch between using bitly and another tracking service.

The subscribe links I am thinking of directory services and niche lists rather than player apps. I have just noted that people often push their Apple or Spotify links even when they have a landing page. Creators clearly have a preference for where people sign up for various reasons. Somehow including something for that within the feed seems reasonable.
Whether an actual deep link is better than just a list of tags for preference is open to question, but I would push for it to be links, just for tracking flexibility.

Part of the reason for it is also strong hints to Google.
Looking at the way Google Podcasts is being used as a featured snippet atm is concerning to the point I would explore adding hard links in feed description and every episode.
A strong hint at this stage seems a better route. 

Just think what used to be done with RSS and Feedburner
A link to canonical for an article was a massively popular plugin
Adding related posts to feeds automatically
Feed widgets at the bottom of every post (a Feedburner feature - I made then for Sphinn and a few other services)


Also, don't forget a podcast being syndicated is duplicate content, just like article distribution of old, or posting on Medium but having a canonical set to your own domain. Eventually, there might be a time when a canonical has to be set as well.

**Comment by jamescridland** [comment]
Thanks so much for your thoughts!

Standard RSS, which this builds on, has a link to the podcast's website ("home"), as well as a link for each episode. (This ought to be the canonical link, but this is outside our scope here).

This spec also includes IDs over to Spotify, Apple and other spaces (podcast:id). Far from prioritising the proprietary services, it's open to all.

RSS feeds, because they're a different mimetype, are unlikely to get confused with duplicate content. Since the links point to the canonical HTML page, that's the hint for any search engine. Google has additional standards to link from the HTML page back to the RSS feed.

Service migration is also outside our scope - but we've a strong standard for this, OPML, which I personally used just yesterday to migrate my subscriptions from Pocket Casts to AntennaPod.

All this is great feedback, thanks. I'll close this for now, since I think we're all good with these, but thank you so much for your comments - always good to give these ideas a good check.
