### ISSUE TITLE
podcast:id needs URL

### ISSUE THREAD

**Issue by andybeard** [Podcastindex-org/podcast-namespace#38]
Service slugs historically in open source are exclusionist.

Here is some context

https://wordpress.org/support/article/embeds/

It is really hard for a video or podcast service with a cool player to get on that list.
For oEmbed to work, you have to either get a blog owner to reduce security or install a custom plugin.
Even embedly (now owned by Medium) hasn't managed to get on that list

The open-source project becomes a gatekeeper for what is acceptable use

You can have a list of common slugs, but anyone should be able to just use a new one for their service
You need to have a URL

In that way even if the gatekeepers of the common list don't include you, it can still work.

Thus podcast:id needs to follow the same format as podcast:funding & podcast:social

It could be argued that if you have the URL, then the service slug is actually redundant and adds maintenance overhead
Exploding a URL for a service name isn't rocket science.

podcast:funding you are going to end up with people defining 100 different options... just wait. Affiliate links to everything they can think of, links to their sales page for various products etc.

But open standards are better than exclusion

**Comment by tomrossi7** [comment]
@andybeard I see what you mean and I agree that we shouldn't be excluding any services that may not even exist today. I think we should avoid defining the universe of "services" and corresponding IDs and stick with URLs whenever possible.

**In Phase 1:**
I can see the change for `funding`. As you said, with the URL, the service slug is additional overhead that adds a trivial amount of functionality.
`<podcast:funding title="[user provided note (string)]">[url for the show at the platform]</podcast:funding>`

The `platform` one is harder. @daveajones currently Buzzsprout integrates with 17 different directories -- and we add more all the time. Is the proposal that each of these would be provided in the format below?
`<podcast:id platform="[service slug]">[the id string]</podcast:id>`

**Comment by daveajones** [comment]
Agreed. Will change the id tag to take a url also.

The slugs file here is very open. Anyone can submit a PR to add to it. As long as what they submit isn’t pure craziness it’ll get merged.  What we see in the wild will surely differ anyway.  I’ll probably even automate something on our side to show us what’s in use and add periodically.

**Comment by jamescridland** [comment]
@andybeard - with regard to `<podcast:id platform="[service slug]">[the id string]</podcast:id>`

I think keeping the slugs as open as possible for people to add their own is as sensible as we can be. There are good technical reasons why the Wordpress example you give is a little more difficult to get into - embedding of other peoples' code in web pages is a horrid privacy nightmare, and that's - thankfully - nothing we have to worry about here.

I think it might be helpful for the list of acceptable slugs to also have URL expansion rules and marketing names (and, in time, icons) to allow for automated links to them. That would make it even easier for them to be used.

So, I guess I'm expecting a (?) JSON (?) file, showing the slug of `apple-podcasts`, the URL expansion of `https://podcasts.apple.com/us/podcast/feed/id%%id%%`, a marketing name of `Apple Podcasts`, and ideally an SVG file, to aid directories to link. Or even the current breed of "hear a random podcast" apps - none of which are trying to be a full podcast app, and where a link to your full podcast app would help considerably.

This world is full of edge cases, however, and as one example, Apple Podcasts lists my podcast at https://podcasts.apple.com/us/podcast/feed/id1325018583 but for me, a better URL would be https://podcasts.apple.com/au/podcast/feed/id1325018583 since I live in Australia, and this gives me better alternative shows to listen to.

URLs also change - Google Podcasts is only two years old, but has changed its URL structure entirely already. So I'd be keen to consider avoiding a full URL, if only because it adds complication to the podcast hosts to keep all these things updated.

**Comment by andybeard** [comment]
URL changes can happen easily at a number of touchpoints

1. The podcast host can build a URL based on a slug at their end
2. A site such as a directory can add logic to modify URLs if needed
3. The Player host such as Google Podcasts can implement redirects

By keeping it open, I can expect there to even be a service need for there to be blacklists for things like NSFW, Age, Religion, Politically incorrect, etc.
I don't want to go into the ramifications of 2nd and 3rd tier linking and bad neighbourhoods here.

You are defining a standard that will be used by political regimes you might not agree with, hardcore p___, cults, sects and many will have their own players, because western platforms would ban them.

But that is the nature of open standards

**Comment by daveajones** [comment]
I get your drift.  And, perhaps those things will happen.  This ultimately comes down to writing a spec and then seeing what people do with it in the real world.  Then changing the spec to match what's going on in practice.  I'm committed to maintaining this spec in an open, flexible way.  We'll see what happens.
