### ISSUE TITLE
Need function comparable to robots.txt, but to guide podcast indexers

### ISSUE THREAD

**Issue by vandys** [Podcastindex-org/podcast-namespace#44]
This namespace element was motivated by a situation where a podcast approached podcastindex, noting that they had _two_ feeds for their podcast (one for most people, another motivated by their Chinese audience), and wanted the latter to be omitted from podcast index.  This request was forwarded, and handled manually.  But it would be nice if a podcast RSS feed could directly annotate whether it should be indexed, without human intervention.

This problem has similarities to the robots.txt file, used to guide whether search engines should index a site in whole, part, or not at all.  But since an RSS feed is complete unto itself, most likely one or so XML fields is preferred to a separate file.

The goal is to permit a podcast's RSS feed indicate which indexers should scan it and publish results.  Alternatively, it might be helpful to indicate which indexers should *not* scan/index it.

Each podcast indexer is probably associated with a standard domain name (spotify.com, podcastindex.org, etc.).  This pattern match allow/disallow will most likely operate with respect to this domain name.

This ticket will serve as a focus point for discussion of the mechanism.  When RSS element name(s) are published (or some other mechanism is accepted), it can be closed.

**Comment by jamescridland** [comment]
This looks a great idea. There is already an iTunes and a Google Play block tag - both named after expired brands, interestingly enough. Frustratingly, Google recognise both iTunes and Google tags as blocking.

This looks like a near replication of the podcast:id tag, perhaps, using slugs for each service and the command "block". Most certainly one for phase 2. Do you feel up to writing a suggestion?

**Comment by jamescridland** [comment]
PS: perhaps here's where my timezone works better. @vandys is this what you had in mind? I'm making this up as I go along:

----

**<podcast:block (allow="[service slug]") (block="[service slug]") />**

(optional - in channel tag only)

A block request, to one or more platforms, or an overall block request for all platforms. This is intended to allow a podcaster to request not being listed in a specific directory - or to request not being listed at all. It uses the [service slugs](https://github.com/Podcastindex-org/podcast-namespace/blob/main/serviceslugs.txt) data which already exists for other elements. Support of this tag will benefit podcast directories by significantly lessening the amount of "please could you remove my listing" emails.

Examples:

* `<podcast:block />`- this blocks ALL platforms
* `<podcast:block allow="pandora" />` - this **blocks** ALL platforms except Pandora.
* `<podcast:block allow="pandora,iheartradio" />` - this **blocks** ALL platforms except Pandora and iHeartRadio
* `<podcast:block block="spotify" />` - this **allows** ALL platforms except Spotify.
* `<podcast:block block="spotify,pandora" />` - this **allows** ALL platforms except Spotify and Pandora

Notes:
* If the `<podcast:block />` tag is not inserted, the default is to allow ALL platforms to index this RSS feed.
* URLs with HTTP Basic Auth credentials - like `https://user:pass@example.com/secret-rss.xml` - should not be indexed by any platform for public consumption. (They may be indexed for individual use, but should never appear in search).
* Users of this tag should also be aware of the proprietary `<itunes:block>` and `<googleplay:block>` tags.
* Use of this tag is not a guarantee.

To keep things simple, for the first phase this is not intended for use at episode level.

**Comment by vandys** [comment]
I get cognitive dissonance when a "block" section has an "allow"!  I'm also a complete hater of XML, but since we're using it here, lists should really be sub-elements?
<podcast:indexers>
 <allow>pandora.com</allow>
 <allow>podcastindex.org</allow>
 <block />
</podcast:indexers>

If podcast:indexers is absent, or you fall off the end of the list, you allow.  Matches are by a domain (so that we're not just playing to entities big enough to own portions of the RSS podcast namespace).  An empty block/allow serves as a default answer, so in this case default is to block indexing.

Treatment of feeds requiring authentication is outside the scope of this ticket, which is focused on indexers/block/allow.  A given indexer, if it has laid hands on an authentication token, has probably also entered into an agreement which will determine if/how they can use that token.

**Comment by mattbasta** [comment]
Is there a compelling reason _not_ to simply rely on `robots.txt`? It feels like this proposal reinvents the wheel unnecessarily, when many podcast indexing services already respect `robots.txt` correctly.

This is a very deep rabbit hole, as well. One may want to block one service from a company but not another (e.g., Google Play versus Google Podcasts). Services publish their bot names for use in robots.txt. Prescriptively defining slugs for third parties limits their ability to accommodate their own product development.

**Comment by jamescridland** [comment]
> Is there a compelling reason not to simply rely on robots.txt?

I don't know how many thousands of feeds live on https://feeds.captivate.fm or https://feeds.buzzsprout.fm or wherever: `robots.txt` seems a bit unwieldy. How would you see this working?

> One may want to block one service from a company but not another

Yes, indeed. The slugs should be service slugs, not companies.

> (e.g., Google Play versus Google Podcasts)

That's a bad example - Google Play is closing - but a better example is Google Search vs Google Podcasts. I'm aware of one, large, international podcasting organisation who would love

```
<podcast:indexers>
  <allow>google-podcasts</allow>
  <block>google-search</block>
</podcast:indexers>
```

...but I agree, the slug list (which I'd really like to be a generic one for all our uses here) should ideally be based on product, not on company.

With the above, I've no idea what happens if `apple-podcasts` shows up. Are they allowed? Or blocked?

> Services publish their bot names for use in robots.txt.

They really don't, though. I've spent the last six months reporting countless bugs for non-existent [RSS useragents](https://github.com/opawg/podcast-rss-useragents). Which, depressingly, has its own slug list!

> Prescriptively defining slugs for third parties

Everyone is welcome to define their own slugs; but without someone making a decision, we can't offer podcasters the control they want or deserve - so a prescriptive start is probably the pragmatic choice.

What's the best way of proceeding? I'm a real fan of giving podcasters control - or, at least, requesting that control. [I've written articles about it](https://medium.com/@JamesCridland/how-to-get-the-bbc-back-into-google-podcasts-6400f16e627b). Do you have a suggestion for how we reword this?

**Comment by mattbasta** [comment]
@jamescridland I think you're proving my point. Robots.txt services the exact use case presented here: controlling access to crawlers. If a crawler is going to ignore robots.txt, it'll ignore this. And any crawler which respects robots.txt does indeed publish information on how to target it in a robots.txt.

I, as a developer, shouldn't need to register a slug in the spec so that people can block me. I'll just publish that myself. This even works at a product level: I mentioned Google services because they supported that exact functionality. Is there a meaningful argument to show that this proposal adds significant value over the status quo?

**Comment by vandys** [comment]
> @jamescridland I think you're proving my point. Robots.txt services the exact use case presented here: controlling access to crawlers. 

robots.txt is highly tuned to web servers, and bots accessing web pages.  I think we can agree that User Agent can indeed reflect a unique crawling service (I don't know if "slug" is an industry term).  But unlike a web server, we can not assume that because you have an RSS feed, you have the ability to store files anywhere else on the hosting server of the RSS.  So we really do have to store it within the RSS XML itself.

Unlike a web server in general, there is no hierarchy of pages within an RSS feed for a podcast.  We want you to include the podcast, or not.  Thus we end up with XML contents in the RSS feed expressing the policy--an enumeration of your allow/deny rules intended to guide a given would-be indexer.

**Comment by theDanielJLewis** [comment]
I like this idea. Maybe instead of `allow` inside the tag, it could be `except`. Then it reads easily, "block everything except this."

However, I can anticipate some grammatical confusion over `except` and `accept`.

**Comment by jamescridland** [comment]
@mattbasta I'm finding your language quite aggressive, and I'm not sure why. I'd really like constructive rather than destructive comments here.

There's currently two tags out there in RSS - an iTunes block tag and a Google Play block tag. What this seeks to do is make a tag like that work for all services, not just those two.

Anchor hosts over 600,000 podcasts on the same domain. A robots.txt offering individual control for every single podcaster and every single possible service out there would be unwieldy and extremely large.

Every other part of a podcast's metadata is within the RSS feed. To require a parser to also request a robots.txt doubles the amount of HTTP requests made, and complicates existing parsers. I am unaware of any evidence that anyone - with the exception of Google - respects `robots.txt` for podcast ingestion.

Podcast parsers have not published their useragents - I'd know, since I've spent a long time cataloguing them. Many were simply using default library UAs. I'm proud of the work I've done here; and with the published list we can make a provider list easily.

Further, this is good for the entire ecosystem. If I object to Overcast having my podcast in it, I have no control currently apart from hassle Marco. With support for this tag, it removes that friction entirely.

If there's a chance of some constructive commenting - perhaps showing how a sample robots.txt might work - then I'd be very willing to consider an alternative. But the above concerns are real and need be addressed in a constructive and polite way, please.

**Comment by mattbasta** [comment]
@jamescridland My goal here is to have a productive technical discussion. I run a service which ultimately needs to write a parser to respect (or ignore) this, so I'm the target audience for these rules. When defining a spec, it's important to ask whether there's an actual problem being solved, or you end up with something that doesn't help or introduces excessive complexity.

I don't want you to feel attacked by my comments, but defining a spec that's to be broadly used also necessarily involves asking the question "does this help?" I'm trying to be "constructive" here by raising unanswered questions about the premise of a proposal that I am the intended audience of. None of us want this project to go the way of ECMAScript 4, XHTML 2, most of Dublin Core, etc.

- Will Apple and Google replace their tags? Or does this just add "yet another tag"?
- Will other apps adopt this or simply ignore it? What incentive do they have to respect it?
- Does this make podcasting more siloed? Should podcasters have the ability to block individual apps, for monetary reasons or otherwise? Does this exacerbate the issue of platform-exclusive shows?
- How does this benefit listeners?
- The existing block tags apply to directories, not on-device apps. You can still manually subscribe to a feed with the block tag set. How, then, does this offer an improvement over robots.txt, which can be cached? Even if every show on Anchor blocked one or more directories, the robots.txt would be only a few megabytes un-gzipped—likely smaller than many cover art JPEGs.
- Since directories need to opt-in to blocking, and must publish something about what you need to do to block them (even a slug), what advantage does this offer over robots.txt?
- Many apps just use Apple's directory. Blocking Apple already blocks many other apps by default. If this allowed blocking individual apps, you'd be able to find a show (from Apple), but attempting to subscribe would error if the app didn't ignore the tag. Is it an acceptable consequence that listeners will have this experience?

This group should strive for rigor, since you can't take a spec back once it's out in the world. And as someone with skin in the game, I'd appreciate that hard questions are not avoided.

**Comment by daveajones** [comment]
@mattbasta I appreciate your thoroughness, but you’re systematically pissing off every person here with “should” language and a stance that you know everything about everything. We’re not designing HTML6 here. This is some podcast tags.  Every association and standards body that has tried to do this for 10+ years has failed because of the flame wars and endless debates over perfection. I’m not going to let that happen here again.  Everyone will get upset and leave. That’s how it always ends. 

At the end of the day you don’t _have_ to support this namespace. You can ignore it if it doesn’t meet the needs of you or your customers. I’m know some hosts will. If you think we’re all too short sighted or incapable to make this work then please go form a group and start your own thing.  If it’s successful we will support it and you with no hard feelings.

**Comment by jamescridland** [comment]
@mattbasta We all have skin in the game here, that's the point of these discussions. I'm delighted that you have 0.252% of the podcast hosting market: but what I've appreciated in this group is that all contributors have been treated, so far, as equally valued. I'd ask you to strive to do the same, please.

In answer to your questions:

> Will Apple and Google replace their tags? Will other apps adopt this or simply ignore it?

You can say the same about the whole namespace. I have no control over Apple or Google's proprietary nametags or their use of them. I have no control over other services. But, by producing something that is inclusive of their own services, while offering more control for podcasters (including your customers), thus benefiting the ecosystem as a whole, this is a step forward. And **most podcast hosts and apps want to do the right thing by creators.**

Apple requires a legal contract to be signed between a podcaster and Apple for carriage on Apple's platform. Most other services take RSS feeds - whether found using a crawl or pulled from other directories - and no such contract has been signed for distribution. (This massively confuses those from the broadcast world, who are used to carriage contracts, incidentally).

> Does this make podcasting more siloed? Should podcasters have the ability to block individual apps, for monetary reasons or otherwise? Does this exacerbate the issue of platform-exclusive shows?

Yes, creators should have the ability to control where their content appears. But also podcast apps should have the knowledge that they're doing the right thing by creators.

When Luminary came onto the scene, many podcasters decided that they were against Luminary and that they did not want their shows listed on Luminary. The only possible way for them to do this was to contact Luminary by email and ask. A comprehensive blocklist/allowlist would allow a podcast host to, with one click, deny access to Luminary - assuming Luminary were acting responsibly by supporting this tag. (For the record, I'm very cool with Luminary listing my show.)

From the reverse angle, Luminary can feel confident scraping RSS feeds, knowing that there is a simple and well-documented method for any podcaster to, within their RSS feed, ask Luminary not to carry their show.

> How does this benefit listeners?

Listeners can know that the podcast host that they listen to is cool with their show appearing on this service.

> The existing block tags apply to directories, not on-device apps.

Yes, correct. The aim is to block appearance in the directories used in the apps, and from apps like Luminary profiting from creators work against their wishes.

> How, then, does this offer an improvement over robots.txt

Every part of a podcast's metadata is within the RSS feed - that's the point of an RSS feed. To require a parser to also request a robots.txt doubles the amount of HTTP requests made, and complicates existing parsers. I am unaware of any evidence that anyone - with the exception of Google - respects robots.txt for podcast ingestion. 

We put the mimetype of the audio file, its duration and its bytesize, into the RSS feed - rather than require the parser to go and inspect each and every audio file. We could strip all that out, and require the parser to go and load the audio file's HEAD to find out this data. We don't, because every part of the podcast's metadata is within the RSS feed. Control of distribution is already there for iTunes/Google. This proposal seeks to extend this control for everyone.

> Many apps just use Apple's directory. Blocking Apple already blocks many other apps by default.

Perhaps this isn't clear enough. Apple's directory, or the Podcast Index, or Blubrry's directory, gives other people (like Overcast) a selection of RSS feeds to go and parse. Overcast then attempts to parse these RSS feeds itself, to run its own directory and make these shows available in Overcast's directory.

For other creative endeavours, content is individually licenced to distribution - done by contracts and lawyers. Podcasting is relatively unique, in that once you sign a legal contract with Apple to get listed, you appear in all manner of other apps automatically: some of whom you may decide, as a creator, that you don't want to be in. This proposal offers that choice for the creator, which is the right thing to do for podcast creators - who, ultimately, are the only people who should be making these decisions.

Pinecast may not wish to offer this control to your customers. That's absolutely fine, and within your gift to do so. Support for this feature, just like others, is a balance of the cost of implementation vs the competitive advantage that support of these tags offers.

**Comment by jamescridland** [comment]
To help this discussion, from the last 90 days of site logs, please find enclosed a complete list of all robots that have checked robots.txt at least once a day. I serve my RSS file from here.

I can see NPR and Googlebot (used for Google Podcasts), and possibly Amazon Alexa (though their bot is used for many things). However, I see no other podcast services here. Let's move on from this debate.

[robots.txt](https://github.com/Podcastindex-org/podcast-namespace/files/5426762/robots.txt)

**Comment by vandys** [comment]
Time to try and list the takeaways from this discussion:
```
<podcast:indexers> with allow/block, as compared <podcast:block-indexers> with <except>this-one</except>
   They are certainly logically equivalent, but I feel like negative logic will confuse most mortals

<accept>domain</accept> is not sufficient; there are _parts_ of an entity which you might want to deflect, while
 permitting others.  I need clarity on "slug", or do we use a more generic "service name" as what to match?
 How do we say yes to Google Play, but no to Google search?  Perhaps "domain[-service]".  So:
  <accept>google.com-play</accept>
  <block>google.com</block>
 then just the Play part is accepted, all other Google services are requested to steer clear.
 By prefixing with domain, we don't have to get into the registry business; let the registrars handle that!

 I always shy from regular expressions, so would like to make this a string/substring match semantic if we can
  make it sufficient to the task?  I also always try to normalize the semantics to lower case, to avoid the tedium
  which always otherwise arrives.  (Precedent is DNS names, which are case insensitive.)
```

**Comment by jamescridland** [comment]
Thanks.

The [service slugs are in here](https://github.com/Podcastindex-org/podcast-namespace/blob/main/serviceslugs.txt) which are used here for other things. Would they work?

**Comment by vandys** [comment]
> The [service slugs are in here](https://github.com/Podcastindex-org/podcast-namespace/blob/main/serviceslugs.txt) which are used here for other things. Would they work?

There will eventually be ones which are substrings of others, which I would prefer to avoid.  Then there's the question of industry acceptance, and also the question of who "owns" a value, and how are disputes resolved?  This is where FQDN solves lots of problems for us.

**Comment by daveajones** [comment]
This will be a phase 2+ item for sure so that we can have plenty of time to refine it.  I'll add a wireframe to phase 2 just to have a placeholder there and we can bang it out going forward in a new issue.
