### ISSUE TITLE
<podcast:transcript> rel attribute's necessity is unclear

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#64]
The `rel="captions"` attribute on `<podcast:transcript>` seems to be redundant. From the spec:

> If the rel="captions" attribute is present, the linked file is considered to be a closed captions file, regardless of what the mime type is.

This seems to imply `rel="captions"` is shorthand for `type="application/srt"`, though it only introduces ambiguity. I would strongly suggest removing it unless a clear need for it presents itself.

**Comment by daveajones** [comment]
There are three initial transcript formats listed in the transcripts folder: HTML, JSON and SRT. Since the mime type alone (specifically in the HTML case) doesn’t tell you if the file contains time codes, the rel=“captions” is there as a flag to signal to the app that no matter what the mime type is,  they should expect the file to be time coded and not just a flat transcript. 

I’ll try and think of better wording for this since it has caused confusion once before.

**Comment by tomrossi7** [comment]
@daveajones I don't know if its necessary. For example, if its JSON or SRT, it *has* to have timestamps. The only format that isn't `rel="captions"` is HTML.
