### ISSUE TITLE
Consider requiring HTTPS for all new tag URLs

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#68]
When loading content like chapters, transcripts, etc., consider requiring HTTPS. Apple and others have indicated that they will require feeds to be served over HTTPS in the future. All modern browsers currently warn web users when they are visiting pages which are not served over HTTPS.

Requiring HTTPS provides strong privacy guarantees. Podcasting's distributed nature guarantees some amount of anonymity. However, it's conceivable that ISPs, malicious VPN providers, wifi access points, and others would sniff traffic to serve targeted ads based on content seen in podcast assets. HTTPS support is essentially 100% for all podcast hosting providers, and an overwhelming majority of podcasters today, so this constraint introduces no significant burden to any podcast producer.

**Comment by daveajones** [comment]
I don't disagree with any of this.  But, the problem is that it will also be ignored.  "Requiring" things in a namespace will fail.  People will continue to do what they want.  It could be said then, that maybe it doesn't hurt to require it.  But, my own opinion is that "require" language scares people off in general.  It feels like a burden even when it doesn't change much.  I'd like to avoid it if possible.

**Comment by tomrossi7** [comment]
I can imagine this being strongly recommended when the podcastindex.org/feed_validator goes live!

**Comment by daveajones** [comment]
"Recommended" feels better.  It's really the only thing we can do.  The apps and aggregators will make their own decisions, regardless of what this spec says.  Many apps may "require" TLS but have the certificate validation property disabled because it produces errors (like it should) and they don't want to bother with it.  There can be breakage all down the chain is what I'm saying.

**Comment by mattbasta** [comment]
It doesn't have to be ignored:
- Call it out in validators
- Require podcast apps to ignore non-HTTPS URLs

If the spec is ignored, the requests fail. Browsers (and by proxy, HTTP clients) already intelligently ignore some types of errors which are overly pedantic. Certificate errors would be blocking the feed download anyway (this is the behavior today) so making this a requirement does not add an operational hurdle for anyone except folks who have ignored Google SEO requirements for ten years. 

This is already something that's abused today, it's not a nebulous hypothetical threat.

**Comment by daveajones** [comment]
`Call it out in validators`

This is a good place for this to happen.

Been thinking about this and I can see it as just wording that is common sense.  If they ignore it, so be it.  They break at some point, which is on them.

I'm cool with it.  Will add.
